### ISSUE TITLE
Bug: Uploading of new models super slow 

### ISSUE THREAD

**Issue by ClemensBeck** [thedworak/dfg_3dviewer#44]
* [x] @thedworak Times for Uploading are super long (up to 3-4 minutes) even for 90KB still files, please check it

**Comment by ClemensBeck** [comment]
Issues is solved

**Comment by igorbajena** [comment]
Today I discovered during tests with Jan Lutteroth, that problems still exists, but not processing of ZIP files is very slow. 7 MB model took around 5 minutes to load.

**Comment by ClemensBeck** [comment]
@igorbajena Will check it

**Comment by ClemensBeck** [comment]
@igorbajena Since I'm migrating all the isuses to the new github repo. Is this isue still open?

**Comment by igorbajena** [comment]
Yes, most of the models load very fast. The only exceptions are large models, which take around 1 minute and after loading, they can freeze the whole page for a few moments. Like here: https://3d-repository.hs-mainz.de/wisski/navigate/2270/view
But I would close this issue, eventually open a new one on how to handle bigger models more sufficiently.

**Comment by ClemensBeck** [comment]
@igorbajena All right. I will close the issue.
