### ISSUE TITLE
Problem with displaying file from RAR and TAR

### ISSUE THREAD

**Issue by igorbajena** [thedworak/dfg_3dviewer#77]
![Image](https://github.com/user-attachments/assets/6ed46966-11ff-43e6-b951-53ffbec1509d)

As mentioned above: https://repository.covher.eu/wisski/navigate/5591/view

**Comment by igorbajena** [comment]
The same applies to TAR files: https://repository.covher.eu/wisski/navigate/5595/view

**Comment by thedworak** [comment]
Unrar wasn't available, so installed unrar-free and added it to the instructions.
Some cases can be related to: 
#76

**Comment by thedworak** [comment]
Should be solved since last week, there were missing libraries for rar

**Comment by igorbajena** [comment]
TAR and RAR still does not work. See: 
TAR: https://repository.covher.eu/wisski/navigate/6079/view
RAR: https://repository.covher.eu/wisski/navigate/6075/view

**Comment by thedworak** [comment]
I was trying to fix it, but still the problem persists. I did two archives in two different ways, but problem is the same:
gzip: stdin: unexpected end of file tar: Child returned status 1 tar: Error is not recoverable: exiting now

**Comment by igorbajena** [comment]
I remove then TAR and RAR from list of supported formats for now.
